Project\CommentBundle\Entity\Comment:
    type: entity
    table: comments
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: '522'

    manyToOne:
        user:
            targetEntity: Bp\CommonBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
