parameters:
#    bp_common.example.class: Bp\CommonBundle\Example

services:
#    bp_common.example:
#        class: %bp_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
